### ISSUE TITLE
[FEATURE]: Destriping for MIRI data

### ISSUE THREAD

**Issue by wjcramer** [PhangsTeam/pjpipe#55]
I'm very intrigued by the success you've had destriping the NIRCam data. I have MIRI data in F560W and F770W that also has what looks like similar amounts of striping as the NIRCam data shown in your paper. I was wondering if the striping part of the pipeline can also be applied to MIRI data in some way?

**Comment by thomaswilliamsastro** [comment]
Interesting...we don't see it so much in our data, which is why we didn't worry about this. It may also be improved with the [new emicorr step](https://jwst-pipeline.readthedocs.io/en/latest/jwst/emicorr/index.html#emicorr-step) The code could definitely be wrangled to work on MIRI data but would require a bit of refactoring. Do you have any images that show off the noise? Particularly interested in the direction of any "stripes" and if they look to be consistent across the whole imager

**Comment by wjcramer** [comment]
Here's an example of the striping in the F560W MIRI filter, it does look consistent across the full extent of the image.

<img width="386" alt="Screenshot 2024-02-02 at 12 19 33 PM" src="https://github.com/PhangsTeam/pjpipe/assets/87668901/10df7a14-4924-40b6-86c4-b51b84633255">

**Comment by thomaswilliamsastro** [comment]
This was brought up by @jchastenet who's been working on ngc891 which seemed to have pretty similar issues until the background observations were subtracted. Then it kind of got rid of the worst of this. I think this might also be causing the problems you have with a background gradient across the image, since the tiles aren't really "flat" until a background has been subtracted. I'm going to try and get a setting that will allow you to specify background from the filename themselves, so you can hook this in and hopefully everything will be magically improved. It'll probably take me a couple of days to find the time, but I'll try and get this done ASAP

btw, I'm guessing since you've now successfully run through the pipeline I can now close #54 ?

**Comment by thomaswilliamsastro** [comment]
@wjcramer I've just pushed up a branch that allows you to select backgrounds via filename:

```
pip3 install git+https://github.com/PhangsTeam/pjpipe.git@background-filename
```

the way to do this is in the config file for the lv2 step you want something like:

```
bgr_check_type = 'filename'
bgr_background_name = 'jw02107018002'
```

where bgr_background_name can be either a string or a list, depending on how you want to match things. If the filename contains any of the `bgr_background_name`s, it'll flag as a background and process as such. I'm hoping this will improve the striping you're seeing and possible make the background level matching better as well

**Comment by wjcramer** [comment]
I'm getting a crash with:

bgr_check_type = 'filename'
bgr_background_name = [
    'jw02433002001_02101_00001_mirimage_rate.fits',
    'jw02433002001_02101_00002_mirimage_rate.fits',
]

Traceback (most recent call last):
  File "/Users/wcramer2/Desktop/pjpipe/run_reprocessing.py", line 28, in <module>
    pjp.do_pipeline()
  File "/Users/wcramer2/miniconda3/envs/jwst/lib/python3.11/site-packages/pjpipe/pipeline.py", line 513, in do_pipeline
    step_result = lv2.do_step()
                  ^^^^^^^^^^^^^
  File "/Users/wcramer2/miniconda3/envs/jwst/lib/python3.11/site-packages/pjpipe/lv2/lv2_step.py", line 127, in do_step
    asn_files = self.create_asn_files(
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wcramer2/miniconda3/envs/jwst/lib/python3.11/site-packages/pjpipe/lv2/lv2_step.py", line 172, in create_asn_files
    tab = get_obs_table(
          ^^^^^^^^^^^^^^
  File "/Users/wcramer2/miniconda3/envs/jwst/lib/python3.11/site-packages/pjpipe/utils/utils.py", line 480, in get_obs_table
    parse_fits_to_table(
  File "/Users/wcramer2/miniconda3/envs/jwst/lib/python3.11/site-packages/pjpipe/utils/utils.py", line 522, in parse_fits_to_table
    raise Warning(f"check_type {check_type} not known")
Warning: check_type filename not known

I've tried manually loading in the files in question:

>>> from stdatamodels.jwst import datamodels
>>> im = datamodels.open(file)
>>> print(im)
<ImageModel(1024, 1032) from jw02433002001_02101_00001_mirimage_rate.fits>
>>>print(im.meta.target.proposer_name.lower())
>>>ngc-891-insert

We called the background observation target ngc-891-insert and the regular data ngc-891. I included in the config files my list of targets as:

# List of targets
targets = [
    'ngc891',
    'ngc-891-insert',
]

Is there something I'm missing?

**Comment by thomaswilliamsastro** [comment]
Ah I see, is the ngc-891-insert data also downloaded into the ngc891 folder? In which case you don't need that second target.

For the error, it should be fine if you properly install the branch: `pip install git+https://github.com/PhangsTeam/pjpipe.git@background-filename` (you might want to do a pip uninstall pjpipe before to make sure it's cleared out)
